# general configuration
url: "http://chalkos.github.io"
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/compass.png"
  # author will appear under the avatar (optional)
  author: "Bruno Ferreira"
  # tagline will appear under the title (optional)
  tagline: "Postgraduate in Informatics Engineering at Minho University and Programmer Analyst at Keep Solutions"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

social:
  github: {icon: github, link: 'link/github/', url: 'https://github.com/chalkos'}
  linkedin: {icon: linkedin-square, link: 'link/linkedin/', url: 'https://pt.linkedin.com/in/chalkos'}
  stackoverflow: {icon: stack-overflow, link: 'link/stackoverflow/', url: 'http://stackoverflow.com/users/1483200/chalkos'}
  contact: {icon: envelope, link: 'mailto:chalkos@chalkos.net'}


# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
